### PR TITLE
fix: local logout should not dismiss token session

### PR DESCRIPTION
**Pull request by nomagick**
Don't dismiss the token session if the token is from the environment variable.

When logout is called, it means to remove the token from the config file.

### CODE REVIEW

**Review by mapleeit — CHANGES_REQUESTED** [review]
Let’s hold the PR and try to find the real problem here. It doesn’t really make sense if we dismiss the token from env by default.

**Comment by nomagick** [comment]
Currently, it dismiss the token from env, this PR is to change that and only dismiss the local config file token

**Comment by mapleeit** [comment]
I see. Make sense. Can we add some tests for it?

**Comment by nomagick** [comment]
Not so easy to test the logout behaviour...

**Comment by mapleeit** [comment]
Simple unit test should work. 

btw, can we distinguish between session token from personal access token via some APIs?

**Comment by nomagick** [comment]
> btw, can we distinguish between session token from personal access token via some APIs?

https://api.hubble.jina.ai/v2/rpc/user.session.getRaw

**Review by mapleeit — APPROVED** [review]

**Pull request merged**
