### PR TITLE
refactor: add session-id in request's header for better error tracking

### PR DESCRIPTION
**Pull request by floralatin**
Add session-id as tracking id in request's header for better error tracking

### CODE REVIEW

**Comment by nomagick** [comment]
Does this have circular import issues?

I don't think we need to add so much version info in SDK.

Just a simple trace id would be enough.

I would prefer this id be injected in query params.

**Comment by delgermurun** [comment]
If trace id is enough, let's add only this as Yanlong said.

If we need full version meta infos, we shouldn't duplicate it. This is already exists in `executor/helper.py`.
Maybe need to create general `helper.py`.

**Review by delgermurun — CHANGES_REQUESTED** [review]
If trace id is enough, let's add only this as Yanlong said.

If we need full version meta infos, we shouldn't duplicate it. This is already exists in `executor/helper.py`.
Maybe need to create general `helper.py`.

**Comment by floralatin** [comment]
> Does this have circular import issues?

No, the functions  in `utils/api_utils.py` so there is no  circular import issues.

**Comment by floralatin** [comment]
> Just a simple trace id would be enough.
> If trace id is enough, let's add only this as Yanlong said.

Now we just set `session_id` in header of every request.

**Review by nomagick — APPROVED** [review]

**Comment by delgermurun** [comment]
@floralatin fyi, this is not refactor. CI assumes refactor has no fix or feature, therefore no release.

I just pushed empty commit to trigger release CI.

**Comment by floralatin** [comment]
> CI assumes refactor has no fix or feature, therefore no release.

@delgermurun  I see, thank you so much for doing it. I'll pay attention to this next time

**Pull request merged**
