### PR TITLE
feat: notebook login

### PR DESCRIPTION
**Pull request by Andrei997**
Ref #78 

**This PR improves the login experience in notebook-like environments (jupyter, google colab).**

There are some images of the new design, attached below.

**Login prompt**
Screen Shot 2022-10-14 at 12 20 37

**Authenticate in browser prompt**
Screen Shot 2022-10-13 at 14 15 39

**Success**
Screen Shot 2022-10-13 at 14 21 55

**Error**
Screen Shot 2022-10-13 at 14 21 21

### CODE REVIEW

**Comment by bwanglzu** [comment]
Like it! Great work!

**Comment by Andrei997** [comment]
Thanks @bwanglzu, that worked :D

**Review by mapleeit — CHANGES_REQUESTED** [review]
Looks good to me. 

Before merging, let's also modify readme [here](https://github.com/jina-ai/jina-hubble-sdk/blob/main/README.md#faq-frequently-asked-questions)

**Comment by Andrei997** [comment]
> Before merging, let's also modify readme [here](https://github.com/jina-ai/jina-hubble-sdk/blob/main/README.md#faq-frequently-asked-questions)

Good catch, the Readme has been updated.

**Review by mapleeit — APPROVED** [review]

**Pull request merged**
